# Projekt-Informationen
site_name: Bioco Web-Projekt Doku
site_url: https://docs.bioco.ch/
site_author: Bioco-Team
copyright: Copyright &copy; 2026 Bioco

# Konfiguration
theme:
  name: material
  language: de
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      primary: green
      accent: light-green
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight

# Erweiterungen
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition # Wichtig f√ºr die farbigen Hinweis-Boxen

# Navigation
nav:
  - Start: index.md
  - Fuer Redakteure:
    - Uebersicht: redaktion/index.md
    - Anleitung: redaktion/anleitung.md
    - Strukturhandbuch: redaktion/strukturhandbuch.md
  - Governance: governance.md
  - Technisch:
    - Uebersicht: technisch/index.md
    - ProcessWire Setup: technisch/setup-processwire.md
    - MkDocs Setup: technisch/setup-mkdocs.md
    - API Dokumentation: technisch/api.md
  - SEO:
    - Uebersicht: seo/index.md
    - Strategie: seo/strategie.md
    - Umsetzung: seo/umsetzung.md